/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Study_Soft\\boke\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-b249813e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b249813e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-41aad648",
    path: "/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41aad648").then(next)
    },
  },
  {
    path: "/git/index.html",
    redirect: "/git/"
  },
  {
    name: "v-00d6c237",
    path: "/git/git%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00d6c237").then(next)
    },
  },
  {
    path: "/git/git笔记.html",
    redirect: "/git/git%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: "/git/git笔记.html",
    redirect: "/git/git%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]