/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "M的个人博客",
  "description": "My dream",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Simplicity First",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Vue-Powered",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Performant",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b249813e",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/git/",
      "relativePath": "git/README.md",
      "key": "v-41aad648",
      "path": "/git/"
    },
    {
      "title": "git笔记",
      "frontmatter": {
        "title": "git笔记",
        "sidebarDepth": 1
      },
      "regularPath": "/git/git%E7%AC%94%E8%AE%B0.html",
      "relativePath": "git/git笔记.md",
      "key": "v-00d6c237",
      "path": "/git/git%E7%AC%94%E8%AE%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "一、git概述",
          "slug": "一、git概述"
        },
        {
          "level": 2,
          "title": "二、git常用命令",
          "slug": "二、git常用命令"
        },
        {
          "level": 2,
          "title": "三、分支",
          "slug": "三、分支"
        },
        {
          "level": 2,
          "title": "四、远程仓库",
          "slug": "四、远程仓库"
        },
        {
          "level": 2,
          "title": "五、在Idea中使用git",
          "slug": "五、在idea中使用git"
        },
        {
          "level": 2,
          "title": "六、在Idea中使用github",
          "slug": "六、在idea中使用github"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间：",
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "git",
        "link": "/git/git笔记"
      },
      {
        "text": "External",
        "link": "https://baidu.com"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese"
          },
          {
            "text": "English",
            "link": "/language/English"
          }
        ]
      }
    ],
    "sidebar": {
      "/git/": [
        "git笔记"
      ],
      "/": [
        ""
      ]
    }
  }
}